# Generated by Django 5.1.3 on 2024-12-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
